// build-hero.js - Builds Hero.tsx with full premium phone mockup
const fs = require('fs');
const path = require('path');

const lines = [];
const add = (s) => lines.push(s);
const blank = () => lines.push('');

add("import Link from 'next/link';");
blank();
add('export default function Hero() {');
add('  return (');
add('    <>');
add('      <section className="pt-32 pb-20 px-6 overflow-hidden">');
add('        <div className="max-w-6xl mx-auto grid md:grid-cols-2 gap-12 items-center">');
add('          <div>');
add('            <div className="inline-block bg-emerald-100 text-emerald-700 px-4 py-2 rounded-full text-sm font-bold mb-6">');
add('              AI Coach For Students');
add('            </div>');
add('            <h1 className="text-5xl md:text-6xl font-serif font-bold mb-6 leading-tight text-gray-900">');
add('              Your scattered work becomes career proof');
add('            </h1>');
add('            <p className="text-lg text-gray-600 mb-8">');
add('              GitHub, Kaggle, certificates, projects—all over the place. ORIN transforms them into verified proof cards, an AI coach who guides you daily, and real opportunities that match your proof.');
add('            </p>');
add('            <div className="flex gap-4 flex-wrap mb-6">');
add('              <Link href="/signup" className="btn-green px-6 py-3 rounded-lg font-semibold">');
add('                Start Building Proof');
add('              </Link>');
add('              <button className="border-2 border-gray-300 px-6 py-3 rounded-lg font-semibold hover:bg-gray-50">');
add('                Watch Demo');
add('              </button>');
add('            </div>');
add('            <p className="text-sm text-gray-500">');
add('              ✓ Free forever tier • ✓ No card needed • ✓ 5,000+ active students');
add('            </p>');
add('          </div>');
blank();
add('          <PhoneMockup />');
add('        </div>');
add('      </section>');
blank();
add('      <style>{styles}</style>');
add('    </>');
add('  );');
add('}');
blank();
add("const styles = `");
add('  .grad-emerald { background: linear-gradient(135deg, #059669 0%, #d97706 100%); -webkit-background-clip: text; -webkit-text-fill-color: transparent; background-clip: text; }');
add('  .btn-green { background: linear-gradient(135deg, #059669, #10b981); color: white; font-weight: 500; transition: box-shadow 0.3s ease; }');
add('  .btn-green:hover { box-shadow: 0 8px 25px rgba(5, 150, 105, 0.3); }');
add('  .animate-float-slow { animation: floatSlow 6s ease-in-out infinite; }');
add('  .animate-float-slower { animation: floatSlower 7.5s ease-in-out infinite; }');
add('  @keyframes floatSlow { 0%, 100% { transform: translateY(0px); } 50% { transform: translateY(-14px); } }');
add('  @keyframes floatSlower { 0%, 100% { transform: translateY(0px) rotate(0deg); } 50% { transform: translateY(-10px) rotate(1deg); } }');
add('  @keyframes progressFill { 0% { stroke-dashoffset: 94.2; } 100% { stroke-dashoffset: 11.3; } }');
add('  .progress-ring { animation: progressFill 1.6s cubic-bezier(0.4, 0, 0.2, 1) forwards; }');
add('  .proof-card-anim { opacity: 0; transform: translateX(-12px); animation: slideInLeft 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards; }');
add('  @keyframes slideInLeft { to { opacity: 1; transform: translateX(0); } }');
add('  .pulse-dot { animation: pulseDot 1.8s ease-in-out infinite; }');
add('  @keyframes pulseDot { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }');
add('  .shine { position: relative; overflow: hidden; }');
add('  .shine::after { content: ""; position: absolute; top: 0; left: -100%; width: 100%; height: 100%; background: linear-gradient(90deg, transparent, rgba(255,255,255,0.25), transparent); animation: shine 3.5s ease-in-out infinite; }');
add('  @keyframes shine { 0% { left: -100%; } 60%, 100% { left: 100%; } }');
add('`;');
blank();

const out = lines.join('\n') + '\n';
fs.writeFileSync(path.join(__dirname, 'Hero.tsx'), out);
console.log('Wrote', out.length, 'chars');
