import type { CoachNote, Opportunity, Proof, User } from "@/lib/types";

export const currentUser: User = {
  id: "u1",
  authUserId: "auth-u1",
  email: "aarav@example.com",
  username: "aarav-gupta-cse",
  fullName: "Aarav Gupta",
  avatarUrl: undefined,
  college: "VIT Vellore",
  year: "third",
  bio: "I build backend systems and solve algorithmic problems.",
  headline: "Backend Engineer & DSA Enthusiast",
  location: "Bengaluru, India",
  websiteUrl: undefined,
  githubUrl: "https://github.com/aarav",
  linkedinUrl: "https://linkedin.com/in/aarav",
  twitterUrl: undefined,
  role: "user",
  accountStatus: "active",
  isProfilePublic: true,
  hideEmail: false,
  emailVerified: true,
  authProvider: "email",
  createdAt: new Date("2024-08-01"),
  updatedAt: new Date("2024-10-01"),
};

export const coachNote: CoachNote = {
  id: "c1",
  userId: "u1",
  content:
    "You have strong graph fundamentals. Add 3 dynamic programming proofs this week to show depth to recruiters.",
  type: "daily",
  actionLabel: "Show me what to build",
  actionUrl: "/dashboard/sources/new",
  priority: 0,
  createdAt: new Date(),
};

export const proofs: Proof[] = [
  {
    id: "p1",
    userId: "u1",
    title: "Internship Backend Microservice",
    description: "Built REST APIs handling 1M+ daily requests.",
    sourceType: "github",
    sourceUrl: "https://github.com/aarav/microservice",
    skillsExtracted: ["Node.js", "Express", "PostgreSQL"],
    skillsUserAdded: [],
    whatItProves: [
      "Backend architecture & API design",
      "Database schema optimization",
      "Production deployment & debugging",
    ],
    verificationStatus: "verified",
    visibility: "public",
    verifiedAt: new Date("2024-09-10"),
    viewCount: 124,
    isHighlighted: true,
    sortOrder: 0,
    metadata: {},
    createdAt: new Date("2024-08-20"),
    updatedAt: new Date("2024-10-01"),
  },
  {
    id: "p2",
    userId: "u1",
    title: "Regional Hackathon 2024 Winner",
    description: "Won regional hackathon among 20 teams.",
    sourceType: "hackathon",
    sourceUrl: "https://drive.example/hackathon-certificate",
    skillsExtracted: ["React", "Team Leadership", "System Design"],
    skillsUserAdded: [],
    whatItProves: ["Rapid prototyping", "Team collaboration"],
    verificationStatus: "pending",
    visibility: "public",
    viewCount: 51,
    isHighlighted: false,
    sortOrder: 1,
    metadata: {},
    createdAt: new Date("2024-09-14"),
    updatedAt: new Date("2024-09-20"),
  },
  {
    id: "p3",
    userId: "u1",
    title: "Codeforces Journey",
    description: "Expert level with 250+ solved problems.",
    sourceType: "other",
    sourceUrl: "https://codeforces.com/profile/aarav",
    skillsExtracted: ["Dynamic Programming", "Graphs", "Greedy"],
    skillsUserAdded: [],
    whatItProves: ["Algorithmic thinking", "Consistency"],
    verificationStatus: "draft",
    visibility: "private",
    viewCount: 17,
    isHighlighted: false,
    sortOrder: 2,
    metadata: {},
    createdAt: new Date("2024-07-01"),
    updatedAt: new Date("2024-10-10"),
  },
  {
    id: "p4",
    userId: "u1",
    title: "Kaggle NLP Challenge",
    description: "Placed in the top 8% using transformer fine-tuning.",
    sourceType: "kaggle",
    sourceUrl: "https://kaggle.com/aarav/nlp-challenge",
    skillsExtracted: ["Python", "Transformers", "ML Ops"],
    skillsUserAdded: [],
    whatItProves: ["Model experimentation", "Data pipeline skills"],
    verificationStatus: "verified",
    visibility: "public",
    verifiedAt: new Date("2024-09-28"),
    viewCount: 64,
    isHighlighted: false,
    sortOrder: 3,
    metadata: {},
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-09-28"),
  },
  {
    id: "p5",
    userId: "u1",
    title: "Cloud Certification (AWS)",
    description: "AWS Certified Cloud Practitioner credential.",
    sourceType: "certificate",
    sourceUrl: "https://drive.example/aws-certificate",
    skillsExtracted: ["AWS", "Cloud Foundations", "Security Basics"],
    skillsUserAdded: [],
    whatItProves: ["Cloud fundamentals", "Infrastructure literacy"],
    verificationStatus: "verified",
    visibility: "public",
    verifiedAt: new Date("2024-08-12"),
    viewCount: 34,
    isHighlighted: false,
    sortOrder: 4,
    metadata: {},
    createdAt: new Date("2024-08-10"),
    updatedAt: new Date("2024-08-12"),
  },
];

export const opportunities: Opportunity[] = [
  {
    id: "o1",
    title: "Backend Engineering Intern",
    company: "Amazon",
    type: "internship",
    requiredSkills: ["Node.js", "PostgreSQL"],
    niceToHave: ["AWS", "Docker"],
    description: "Work on scalable backend services for Amazon's core platform.",
    location: "Bengaluru, India",
    isRemote: false,
    link: "https://amazon.jobs/backend-intern",
    applyDeadline: new Date("2024-11-15"),
    matchPercentage: 82,
    salaryMin: 50000,
    salaryMax: 80000,
    salaryCurrency: "USD",
    source: "Amazon Careers",
    isActive: true,
    postedAt: new Date("2024-10-01"),
    metadata: {},
    createdAt: new Date("2024-10-01"),
    updatedAt: new Date("2024-10-01"),
  },
  {
    id: "o2",
    title: "Software Engineer - New Grad",
    company: "Flipkart",
    type: "job",
    requiredSkills: ["System Design", "REST APIs"],
    niceToHave: ["Java", "Microservices"],
    description: "Full-time role building e-commerce infrastructure.",
    location: "Bengaluru, India",
    isRemote: false,
    link: "https://flipkart.careers/new-grad",
    matchPercentage: 76,
    salaryMin: 30000,
    salaryMax: 50000,
    salaryCurrency: "USD",
    source: "Flipkart Careers",
    isActive: true,
    postedAt: new Date("2024-09-15"),
    metadata: {},
    createdAt: new Date("2024-09-15"),
    updatedAt: new Date("2024-09-15"),
  },
  {
    id: "o3",
    title: "ML Research Apprenticeship",
    company: "Google",
    type: "mentorship",
    requiredSkills: ["Python", "Transformers"],
    niceToHave: ["PyTorch", "TensorFlow"],
    description: "Research apprenticeship in machine learning at Google DeepMind.",
    location: "Remote",
    isRemote: true,
    link: "https://careers.google.com/ml-apprenticeship",
    matchPercentage: 69,
    source: "Google Careers",
    isActive: true,
    postedAt: new Date("2024-09-01"),
    metadata: {},
    createdAt: new Date("2024-09-01"),
    updatedAt: new Date("2024-09-01"),
  },
];
